# Generated by GitHub Copilot on 2026-04-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tintuyendung',
            name='hinh_thuc_tuyen_dung',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tintuyendung',
            name='yeu_cau',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tintuyendung',
            name='quyen_loi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
